name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-22.04, windows-2022, macos-12]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        bash: pip install hatch==1.9.1
      - name: Set up Rust
        bash: rustup show
      - name: Run Lint
        bash: hatch run lint:style
      - name: Run tests
        bash: hatch run test:all
